version: "3.8"
services:
  db:
    container_name: Postgres_py
    image: postgres:16.0
    environment:
      POSTGRES_DB: person-py
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-py:/var/lib/postgresql/data
volumes:
  postgres-py:
